### ISSUE TITLE
a few questions on building the samples

### ISSUE THREAD

**Issue by RallyTronics** [Lugdunum3D/Lugdunum#117]
I am using VS2017, and I had no problems building the libraries.

When running cmake and configuring for the samples I need to specify a LUG_MISC_DIR, not sure where this is supposed to point to.  In addition  I get the following error:

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LUG (missing: LUG_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  F:/Lugdunum/cmake/modules/FindLUG.cmake:180 (find_package_handle_standard_args)
  Macros.cmake:137 (find_package)
  base/CMakeLists.txt:27 (lug_add_sample)

What do  I need to do to get the samples to build?

Thanks!

**Comment by DoumbiaAmadou** [comment]
Hello, I had the same issue in my sample project window. did you find any solution please ? thank.

**Comment by RallyTronics** [comment]
I never found a solution, I ended up switching to [Banshee Engine](https://github.com/BearishSun/BansheeEngine) and haven't looked back.

**Comment by Sumenia** [comment]
You need to specify `LUG_ROOT` in your env in order to make it work. The documentation may not be explicit about this. 
We worked very hard on Lugdunum during two years, it was our end-of-study project. As of today, we finished our study and aren't maintaining it actively. Still up to answer any of your questions though 👍

**Comment by DoumbiaAmadou** [comment]
It's work for me. I  created LUG_ROOT_DIR  set to C:/Program Files/Lugdunum  
and add C:/Program Files/Lugdunum/bin in my path and it's work.  see in attach the screenshot. of my cmake gui 
 ![image](https://user-images.githubusercontent.com/7091807/37608748-a4da4198-2b9b-11e8-9ede-e1948bef580d.png)
