### ISSUE TITLE
Custom asset format loading?

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Lugdunum3D/Lugdunum#46]
Will there be capabilities to specify your own content loading functions. For example if you want to compress all your shaders into a single file with a header pointing to the positions of each shader, and such?

**Comment by saveman71** [comment]
As explained in #45 we are currently in the process of refactoring some major parts of the engine. We are currently developing a resource manager in [`feature-refactor-types-gltf`](https://github.com/Lugdunum3D/Lugdunum/tree/feature-refactor-types-gltf), which is calling `Loader`s, so ultimately you would be able to create your own resource loader.

Also as the branch name hints, we're going to provide a [glTF 2.0](https://github.com/KhronosGroup/glTF/tree/2.0) loader (which will use our [glTF2-loader](https://github.com/Lugdunum3D/glTF2-loader)) and some image loaders which will use [stb_image](https://github.com/nothings/stb/blob/master/stb_image.h). As a summary, glTF would basically answer to your need of compressing/packing all your resources into a single file.

**Comment by LunaTheFoxgirl** [comment]
If you leave some issues open for contributors, i'd happily help you.
